<script setup lang="ts">
/**
 * TemplatesGallery — browseable index of ready-to-run presets.
 *
 * Fetches /templates/index.json (generated by scripts/build_templates_index.py)
 * and renders a filterable list. The full JSON of each preset stays on-demand
 * (single request on "voir" click or download link), so the first paint stays
 * under ~30 kB even with 20+ presets.
 */
import { ref, computed, onMounted, shallowRef } from 'vue'
import { withBase } from 'vitepress'

interface TemplateEntry {
  slug: string
  file: string
  title: string
  description: string
  domain: string
  tags: string[]
  requires_pro: boolean
  requires_plugins: string[]
  version: number
  capabilities: string[]
  step_count: number
  steps: string[]
  size_bytes: number
}

interface TemplatesIndex {
  generated_by: string
  count: number
  items: TemplateEntry[]
}

const items = shallowRef<TemplateEntry[]>([])
const status = ref<'loading' | 'ready' | 'error'>('loading')
const error = ref('')

const query = ref('')
const activeDomain = ref<string | null>(null)
const activeCapability = ref<string | null>(null)
const showProOnly = ref(false)

const expanded = ref<Record<string, any>>({})

onMounted(async () => {
  try {
    const res = await fetch(withBase('/templates/index.json'))
    if (!res.ok) throw new Error(`index.json ${res.status}`)
    const data: TemplatesIndex = await res.json()
    items.value = data.items
    status.value = 'ready'
  } catch (err: any) {
    error.value = err?.message || String(err)
    status.value = 'error'
  }
})

const domains = computed(() => {
  const set = new Map<string, number>()
  for (const it of items.value) set.set(it.domain, (set.get(it.domain) || 0) + 1)
  return [...set.entries()].sort((a, b) => a[0].localeCompare(b[0]))
})

const capabilities = computed(() => {
  const set = new Map<string, number>()
  for (const it of items.value) {
    for (const c of it.capabilities) set.set(c, (set.get(c) || 0) + 1)
  }
  return [...set.entries()].sort((a, b) => b[1] - a[1]).slice(0, 20)
})

const filtered = computed(() => {
  const q = query.value.trim().toLowerCase()
  return items.value.filter((it) => {
    if (activeDomain.value && it.domain !== activeDomain.value) return false
    if (activeCapability.value && !it.capabilities.includes(activeCapability.value)) return false
    if (showProOnly.value && !it.requires_pro) return false
    if (q) {
      const hay = [
        it.slug,
        it.title,
        it.description,
        ...it.tags,
        ...it.capabilities,
      ]
        .join(' ')
        .toLowerCase()
      if (!hay.includes(q)) return false
    }
    return true
  })
})

async function togglePreview(slug: string, file: string) {
  if (expanded.value[slug]) {
    delete expanded.value[slug]
    expanded.value = { ...expanded.value }
    return
  }
  try {
    const res = await fetch(withBase(`/templates/${file}`))
    expanded.value = {
      ...expanded.value,
      [slug]: await res.json(),
    }
  } catch (err) {
    console.error('[templates] preview fetch failed', err)
  }
}

function fmtKb(n: number): string {
  return n < 1024 ? `${n} B` : `${(n / 1024).toFixed(1)} kB`
}
</script>

<template>
  <div class="tg">
    <div v-if="status === 'loading'" class="tg__status">Chargement de l'index des presets...</div>
    <div v-if="status === 'error'" class="tg__status tg__status--error">
      Erreur : {{ error }}
    </div>

    <template v-if="status === 'ready'">
      <div class="tg__controls">
        <input
          v-model="query"
          class="tg__search"
          placeholder="Rechercher un preset, une capability, un tag..."
          type="search"
        />
        <label class="tg__toggle">
          <input v-model="showProOnly" type="checkbox" />
          <span>Pro uniquement</span>
        </label>
      </div>

      <div class="tg__filters">
        <div class="tg__filter-row">
          <span class="tg__filter-label">Domaine</span>
          <button
            class="tg__chip"
            :class="{ 'tg__chip--active': activeDomain === null }"
            @click="activeDomain = null"
          >
            Tous ({{ items.length }})
          </button>
          <button
            v-for="[name, n] in domains"
            :key="name"
            class="tg__chip"
            :class="{ 'tg__chip--active': activeDomain === name }"
            @click="activeDomain = activeDomain === name ? null : name"
          >
            {{ name }} ({{ n }})
          </button>
        </div>

        <div class="tg__filter-row">
          <span class="tg__filter-label">Capability</span>
          <button
            class="tg__chip tg__chip--cap"
            :class="{ 'tg__chip--active': activeCapability === null }"
            @click="activeCapability = null"
          >
            Toutes
          </button>
          <button
            v-for="[name, n] in capabilities"
            :key="name"
            class="tg__chip tg__chip--cap"
            :class="{ 'tg__chip--active': activeCapability === name }"
            @click="activeCapability = activeCapability === name ? null : name"
          >
            {{ name }} ({{ n }})
          </button>
        </div>
      </div>

      <div class="tg__meta">
        <strong>{{ filtered.length }}</strong> preset{{ filtered.length > 1 ? 's' : '' }} affiches
      </div>

      <div v-if="filtered.length === 0" class="tg__empty">
        Aucun preset ne correspond aux filtres.
      </div>

      <ul class="tg__list">
        <li v-for="it in filtered" :key="it.slug" class="tg__card">
          <header class="tg__card-head">
            <div>
              <h3 class="tg__card-title">{{ it.title }}</h3>
              <div class="tg__card-sub">
                <span class="tg__tag tg__tag--domain">{{ it.domain }}</span>
                <span class="tg__tag tg__tag--version">v{{ it.version }}</span>
                <span v-if="it.requires_pro" class="tg__tag tg__tag--pro">Pro</span>
                <span
                  v-for="plug in it.requires_plugins"
                  :key="plug"
                  class="tg__tag tg__tag--plugin"
                >
                  plugin: {{ plug }}
                </span>
              </div>
            </div>
            <div class="tg__card-actions">
              <button class="tg__btn" @click="togglePreview(it.slug, it.file)">
                {{ expanded[it.slug] ? 'Masquer' : 'Apercu' }}
              </button>
              <a
                class="tg__btn tg__btn--primary"
                :href="withBase(`/templates/${it.file}`)"
                :download="it.file"
              >
                Telecharger ({{ fmtKb(it.size_bytes) }})
              </a>
            </div>
          </header>

          <p v-if="it.description" class="tg__desc">{{ it.description }}</p>

          <div v-if="it.tags.length" class="tg__tags">
            <span v-for="t in it.tags" :key="t" class="tg__tag">#{{ t }}</span>
          </div>

          <div class="tg__caps">
            <span class="tg__caps-label">{{ it.step_count }} steps ·</span>
            <code v-for="c in it.capabilities" :key="c" class="tg__cap-code">{{ c }}</code>
          </div>

          <details v-if="it.steps.length" class="tg__steps">
            <summary>Etapes ({{ it.steps.length }})</summary>
            <ol>
              <li v-for="(s, i) in it.steps" :key="i">{{ s }}</li>
            </ol>
          </details>

          <pre v-if="expanded[it.slug]" class="tg__preview"><code>{{ JSON.stringify(expanded[it.slug], null, 2) }}</code></pre>
        </li>
      </ul>
    </template>
  </div>
</template>

<style scoped>
.tg { margin: 1.5rem 0; }
.tg__status { padding: 1rem; color: var(--vp-c-text-2); }
.tg__status--error { color: var(--vp-c-danger-1); }

.tg__controls {
  display: flex;
  gap: 0.75rem;
  align-items: center;
  margin-bottom: 0.75rem;
  flex-wrap: wrap;
}
.tg__search {
  flex: 1 1 320px;
  padding: 0.5rem 0.75rem;
  border: 1px solid var(--vp-c-divider);
  border-radius: 6px;
  background: var(--vp-c-bg-soft);
  color: var(--vp-c-text-1);
  font-size: 0.9rem;
}
.tg__search:focus {
  outline: 2px solid var(--vp-c-brand-1);
  outline-offset: -1px;
}
.tg__toggle {
  display: inline-flex;
  gap: 0.4rem;
  align-items: center;
  font-size: 0.85rem;
  cursor: pointer;
  color: var(--vp-c-text-2);
}

.tg__filters { margin-bottom: 1rem; }
.tg__filter-row {
  display: flex;
  flex-wrap: wrap;
  gap: 0.35rem;
  align-items: center;
  margin-bottom: 0.4rem;
}
.tg__filter-label {
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: var(--vp-c-text-3);
  margin-right: 0.25rem;
  min-width: 80px;
}
.tg__chip {
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg-soft);
  color: var(--vp-c-text-2);
  padding: 0.2rem 0.6rem;
  border-radius: 999px;
  font-size: 0.78rem;
  cursor: pointer;
  transition: border-color 0.12s, background 0.12s;
}
.tg__chip:hover { border-color: var(--vp-c-brand-1); }
.tg__chip--active {
  background: var(--vp-c-brand-soft);
  border-color: var(--vp-c-brand-1);
  color: var(--vp-c-brand-1);
  font-weight: 600;
}
.tg__chip--cap { font-family: var(--vp-font-family-mono); }

.tg__meta { font-size: 0.8rem; color: var(--vp-c-text-2); margin-bottom: 0.75rem; }
.tg__empty {
  padding: 2rem;
  text-align: center;
  color: var(--vp-c-text-2);
  border: 1px dashed var(--vp-c-divider);
  border-radius: 8px;
}

.tg__list {
  list-style: none;
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
  gap: 1rem;
}
.tg__card {
  background: var(--vp-c-bg-soft);
  border: 1px solid var(--vp-c-divider);
  border-radius: 10px;
  padding: 1rem;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}
.tg__card-head {
  display: flex;
  justify-content: space-between;
  gap: 0.6rem;
  align-items: flex-start;
  flex-wrap: wrap;
}
.tg__card-title { margin: 0; font-size: 0.98rem; line-height: 1.3; }
.tg__card-sub {
  display: flex;
  gap: 0.3rem;
  flex-wrap: wrap;
  margin-top: 0.25rem;
}
.tg__card-actions { display: flex; gap: 0.35rem; flex-shrink: 0; }

.tg__btn {
  font-size: 0.75rem;
  padding: 0.3rem 0.6rem;
  border-radius: 6px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg);
  color: var(--vp-c-text-1);
  cursor: pointer;
  text-decoration: none;
}
.tg__btn:hover { border-color: var(--vp-c-brand-1); }
.tg__btn--primary {
  background: var(--vp-c-brand-1);
  color: var(--vp-c-white);
  border-color: var(--vp-c-brand-1);
}
.tg__btn--primary:hover { background: var(--vp-c-brand-2); color: var(--vp-c-white); }

.tg__desc { margin: 0; font-size: 0.85rem; color: var(--vp-c-text-2); line-height: 1.5; }

.tg__tag {
  display: inline-block;
  font-size: 0.7rem;
  padding: 0.1rem 0.45rem;
  border-radius: 4px;
  background: var(--vp-c-bg);
  color: var(--vp-c-text-2);
  border: 1px solid var(--vp-c-divider);
}
.tg__tag--domain { text-transform: uppercase; letter-spacing: 0.03em; font-weight: 600; }
.tg__tag--version { font-family: var(--vp-font-family-mono); }
.tg__tag--pro {
  background: var(--vp-c-brand-soft);
  color: var(--vp-c-brand-1);
  border-color: var(--vp-c-brand-1);
  font-weight: 600;
}
.tg__tag--plugin { font-family: var(--vp-font-family-mono); font-size: 0.68rem; }

.tg__tags { display: flex; flex-wrap: wrap; gap: 0.25rem; }
.tg__caps {
  display: flex;
  flex-wrap: wrap;
  gap: 0.3rem;
  align-items: center;
  font-size: 0.75rem;
}
.tg__caps-label { color: var(--vp-c-text-3); }
.tg__cap-code {
  background: var(--vp-c-bg);
  color: var(--vp-c-text-1);
  padding: 0.1rem 0.4rem;
  border-radius: 4px;
  font-size: 0.7rem;
}

.tg__steps { font-size: 0.8rem; margin-top: 0.2rem; }
.tg__steps summary { cursor: pointer; color: var(--vp-c-text-2); }
.tg__steps ol { margin: 0.4rem 0 0.2rem 1rem; padding: 0; color: var(--vp-c-text-2); }

.tg__preview {
  max-height: 360px;
  overflow: auto;
  background: var(--vp-c-bg);
  border: 1px solid var(--vp-c-divider);
  border-radius: 6px;
  padding: 0.6rem;
  font-size: 0.72rem;
  margin: 0.4rem 0 0;
}
</style>
